[build]
default-target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image.name = "bmauto/cross-build-arm64/aarch64-unknown-linux-gnu:main"
image.platform = "linux/arm64"
image.toolchain = ["aarch64-unknown-linux-gnu"]

[target.x86_64-unknown-linux-gnu]
image.name = "bmauto/cross-build-arm64/x86_64-unknown-linux-gnu:main"
image.platform = "linux/amd64"
image.toolchain = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
