FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV CROSS_DEB_ARCH=armhf

COPY ./sources.list.u22 /etc/apt/sources.list

RUN dpkg --add-architecture armhf

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libclang-dev \
    libc6-dev-armhf-cross \
    libgcc-s1-armhf-cross \
    libpam0g-dev \
    g++-arm-linux-gnueabihf \
    curl \
    openssl \
    ca-certificates \
    git \
    pkg-config \
    make \
    cmake \
    golang \
    nasm \
    llvm \
    libc6-dev:$CROSS_DEB_ARCH \
    libssl-dev:$CROSS_DEB_ARCH \
    libtbb-dev:$CROSS_DEB_ARCH \
    libpam0g-dev:$CROSS_DEB_ARCH \
    zlib1g-dev:$CROSS_DEB_ARCH \
    libudev-dev:$CROSS_DEB_ARCH \
    libgstreamer1.0-dev:$CROSS_DEB_ARCH \
    libgstreamer-plugins-base1.0-dev:$CROSS_DEB_ARCH

RUN rm -rf /var/lib/apt/lists/*

RUN printf '%s\n' \
  '#!/bin/sh' \
  'export PKG_CONFIG_DIR=' \
  'export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig' \
  'export PKG_CONFIG_SYSROOT_DIR=/' \
  'exec pkg-config "$@"' \
  > /usr/local/bin/arm-linux-gnueabihf-pkg-config && chmod +x /usr/local/bin/arm-linux-gnueabihf-pkg-config

ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
ENV PKG_CONFIG_armv7_unknown_linux_gnueabihf=/usr/local/bin/arm-linux-gnueabihf-pkg-config
ENV PKG_CONFIG_arm_unknown_linux_gnueabihf=/usr/local/bin/arm-linux-gnueabihf-pkg-config
ENV PKG_CONFIG_ALLOW_CROSS=1
